sudo: false
language: cpp
compiler: gcc
addons:
    apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
          - g++-5
          - gcc-5-locales
          - gcc-5-multilib
          - g++-5-multilib
          - libstdc++6-4.9-dbg
          - libgcc1-dbg
          - libgomp1-dbg
          - libitm1-dbg
          - libatomic1-dbg
          - libasan1-dbg
          - liblsan0-dbg
          - libtsan0-dbg
          - libubsan0-dbg
          - libcilkrts5-dbg
          - libquadmath0-dbg
          - libstdc++-4.9-doc
          - zlib1g-dev
          - libbz2-dev
          - libsnappy-dev
          - tree

before_install:
  - mkdir -p root/bin root/usr/bin root/usr/lib root/usr/include
  - export PATH=`pwd`/root/bin:`pwd`/root/usr/bin:`pwd`/root/usr/local/bin:$PATH
  - export LIBRARY_PATH=`pwd`/root/usr/lib:`pwd`/root/usr/local/lib:$LIBRARY_PATH
  - export CPATH=`pwd`/root/usr/include:`pwd`/root/usr/local/include:$CPATH
  - install /usr/bin/gcc-5 `pwd`/root/usr/bin/gcc
  - install /usr/bin/g++-5 `pwd`/root/usr/bin/g++
  - echo $PATH
  - export
  - wget https://gflags.googlecode.com/files/libgflags0_2.0-1_amd64.deb
  - dpkg-deb -x libgflags0_2.0-1_amd64.deb `pwd`/root/
  - wget https://gflags.googlecode.com/files/libgflags-dev_2.0-1_amd64.deb
  - dpkg-deb -x libgflags-dev_2.0-1_amd64.deb `pwd`/root/
  - gcc --version
  - g++ --version
  - ls /usr/bin/gcc*
  - ls /usr/bin/g++*
  - tree `pwd`/root

script: "./build_tools/build_current_tag.sh"
notifications:
  email: false

before_deploy:
  - export RELEASE_PKG_FILE=$(ls rocksdb*.deb)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: fNBxdwWeiZYIGMPP5QgaIaBjeKqnKZ6YFax5D5drpX/5S0ftMauzKOLs36GhCJYHyDT0aei2+53sN0hogUXWgJbnZFaVrE2KFxuw1OXWu9xtCd7BnMIi1GrFkXo/6oeot1KbSw8BkfU2D+hT8gqGI4PdrEhTKyL5Gh9hcKIijv0=
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  skip-cleanup: true
  on:
    repo: NickCis/rocksdb
    tags: true
