language: cpp
compiler: gcc
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -y -qq gcc-4.9 g++-4.9 zlib1g-dev libbz2-dev libsnappy-dev
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
- wget https://gflags.googlecode.com/files/libgflags0_2.0-1_amd64.deb
- sudo dpkg -i libgflags0_2.0-1_amd64.deb
- wget https://gflags.googlecode.com/files/libgflags-dev_2.0-1_amd64.deb
- sudo dpkg -i libgflags-dev_2.0-1_amd64.deb
script: "./build_tools/build_current_tag.sh"
notifications:
  email: false

before_deploy:
  - export RELEASE_PKG_FILE=$(ls *.deb)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: fNBxdwWeiZYIGMPP5QgaIaBjeKqnKZ6YFax5D5drpX/5S0ftMauzKOLs36GhCJYHyDT0aei2+53sN0hogUXWgJbnZFaVrE2KFxuw1OXWu9xtCd7BnMIi1GrFkXo/6oeot1KbSw8BkfU2D+hT8gqGI4PdrEhTKyL5Gh9hcKIijv0=
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  skip-cleanup: true
  on:
    repo: NickCis/rocksdb
    tags: true
